name: 🔖 Documentation update
description: Improve Documentation
title: "docs:"
labels:
  [
    "📄 aspect: text",
    "🚦status: awaiting triage",
    "✨ goal: improvement",
    "good first issue"
  ]
body:
  - type: checkboxes
    id: read-guidelines
    attributes:
      label: Contributor Guidelines
      description: Please confirm that you have read the [Contributor Guidelines and Discussion](https://github.com/reactplay/react-play/discussions/1598) before submitting this issue or PR.
      options:
        - label: I have read the guidelines and discussion
          required: true

  - type: textarea
    id: improve-docs
    attributes:
      label: What's wrong with the documentation?
      description: Which things do we need to add?
      placeholder: Add description
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Add screenshots to see the demo
      placeholder: Add screenshots
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
          required: true

        - label: I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
          required: true

        - label: I agree to follow this project's [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
          required: true

        - label: I want to work on this issue
        - label: I am a Hacktoberfest contributor
