name: 🔖 Documentation update
description: Improve Documentation
title: "docs:"
labels:
  [
    "📄 aspect: text",
    "🚦status: awaiting triage",
    "✨ goal: improvement",
    "good first issue"
  ]
body:
  - type: textarea
    id: improve-docs
    attributes:
      label: what's wrong with the documentation?
      description: which things do we need to add?
      placeholder: Add description
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Add screenshots to see the demo
      placeholder: Add screenshots
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      options:
        - label: I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
          required: true

        - label: I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
          required: true

        - label: I agree to follow this project's [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
          required: true

        - label: I want to work on this issue