name: '✨ [Feature request]:'
description: Suggest an idea for this project
title: '✨ [Feature request]: '
labels: ["🚦status: awaiting triage", "💻 aspect: code", "⭐ goal: addition"]
body:
  - type: checkboxes
    id: read-guidelines
    attributes:
      label: Contributor Guidelines
      description: Please confirm that you have read the [Contributor Guidelines and Discussion](https://github.com/reactplay/react-play/discussions/1598) before submitting this issue or PR.
      options:
        - label: I have read the guidelines and discussion
          required: true

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time for issuing a feature request!

  - type: textarea
    id: feature-reason
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot / Screenshare
      description: Please add screenshot or screenshare if that helps to describe the feature.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add other additional context about the feature.

  - type: checkboxes
    id: record
    attributes:
      label: Record
      options:
        - label: I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
          required: true
        - label: I want to work on this issue
        - label: I am a Hacktoberfest contributor

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
