name: New Play
description: Add a New Play Request
title: '[Add a Play]: '
labels: ["play request","🚦status: awaiting triage", "💻 aspect: code" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time for creating a new play.

  - type: textarea
    id: about-play
    attributes:
      label: What's the Play about?
      description: Tell us in details about your play.
    validations:
      required: true

  - type: textarea
    id: react-concepts
    attributes:
      label: What ReactJS concept will be used to create this play?
      placeholder: Components, Hooks, React Router ...
    validations:
      required: true

  - type: checkboxes
    id: record
    attributes:
      label: Record
      options:
        - label: I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
          required: true
        - label: I want to work on this issue

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/reactplay/react-play/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
